### ISSUE TITLE
Support for XLIFF parsing?

### ISSUE THREAD

**Issue by bradyisom** [loclapp/locl#2]
It looks like this library only supports downloading and parsing JSON files. However, the Angular CLI workflow does not support extracting to JSON. I see there is a parser for XLIFF files here: https://github.com/angular/angular/blob/master/packages/localize/src/tools/src/translate/translation_files/translation_parsers/xliff2_translation_parser.ts. Is there a way we could get this utility to use that to parse XLIFF files, so we can load them before bootstrapping the application?

**Comment by ocombe** [comment]
Hello!
It's a bad idea to use XLIFF at runtime because parsing XML requires a lot of code (something like 20kb or more minified). As you can see in the link above it requires stuff from the `@angular/compiler` package. If you were to use that at runtime, it would pull a good part of the compiler package!

There are two solutions:
- switch to json completely using the `locl extract` command from `@locl/cli` (which by the way supports code translations, which is not the case of the angular cli right now),
- or use `@locl/cli` to extract as xliff (if you need that format for your translators) and convert the files to json when you bundle the app.
I'm working on the `locl convert` command right now, expect a new release with that before the end of the week.

I will also be working on an advanced json format using json5 which will include the comments/meaning as `// comments` to help the translators

**Comment by bradyisom** [comment]
Got it. Makes sense. Thank you.

**Comment by ocombe** [comment]
Hello, fyi @locl/cli 0.0.1-beta.2 has been released with the `locl convert` command :)
