### ISSUE TITLE
Some questions (FAQ)

### ISSUE THREAD

**Issue by gilsdav** [loclapp/locl#3]
Hello @ocombe,

First thank's for your awesome job with `ngx-translate` which has given rise to other awesome projects like [localize-router](https://github.com/Greentube/localize-router).

I'm really interested by this more integrated solution so I hope not to bother you by launching this FAQ.

My first questions:

* What's the use if it is not possible to **change the language**?
   Because I don't undersand by seeing your documentation or the [Angular one](https://next.angular.io/guide/i18n) how we can change lang. [This article](https://www.softwarearchitekt.at/aktuelles/lazy-loading-locals-with-angular) comes closes but not completely 
* Will you make a **pipe** like the `| translate` ? I personally only use this technic of `ngx-translate`.
* Do the `$localize` works with **`OnPush`** ? Is the value updated when we change the lang ?

**Comment by ocombe** [comment]
Hello !

- You choose the language for your app when it bootstraps and load the translation file accordingly. If the user of your app needs to change the language you need to reload the app somehow (most likely by reloading the page), you can keep the language selected by setting a cookie, changing a parameter in the url, using locale storage, setting a session parameter on the server... it's up to you
- I don't think that a pipe is necessary, `$localize` works in the template with an `i18n` attribute, you can translate text or other attributes (just like the current i18n solution). If you need to translate the result of a binding, most likely you can use the  $localize\`some text\` template string, it's like a function applied on a template string, but if you find a use case that really needs a pipe let me know, it wouldn't be hard to write one
- yes it works with `OnPush`, the value will be updated on your page if the text to translate changes, but like I said previously you can't change the lang without reloading the app (since the translations need to be loaded before the app bootstraps)

**Comment by gilsdav** [comment]
Hello @ocombe 
Is this still the case that "you can't change the lang without reloading the app" ?
I yes, I don't see any reason to go to this new standard solution instead of ngx-translate.
My clients don't want a page reload because they can change lang in the middle of form completion.

**Comment by ocombe** [comment]
Hello!
Yes this is still the case because that's how `$localize` works.
If you really need to change the lang without reloading the page, then this library is definitely not what you need, sorry!

**Comment by gilsdav** [comment]
Sad reality,
So thank's for your awesome ngx-translate ! 😃
